# Identifiez les grandes tendances

Créez un dataframe contenant les informations de population de chaque pays. Calculez le nombre total d’humains sur la planète. Critiquez votre résultat. En cas d’anomalie, analysez et effectuer les corrections nécessaires.

# Question 1 : 

Donnez le résultat de votre calcul pour l'année 2013, ainsi que pour la dernière année  disponible au jour où vous effectuez ce projet

In [2]:
import pandas as pd
import numpy as np

# importation de la table population pour 2013
population_2013 = pd.read_csv("population_2013.csv")

In [ ]:
population_2013.csv

In [2]:
# 'Valeur' mise à la bonne unité
population_2013['Valeur'] = population_2013['Valeur']*1000

# calcul de la population mondiale de 2013
population_2013['Valeur'].sum(min_count=1)

8627069094.0

In [3]:
# le résultat ne semble pas cohérent, après obervation de la base de données, suppression de l'individu Chine en 
# doublon
population_2013 = population_2013.loc[population_2013.Zone != 'Chine', :]

# calcul de la population mondiale de 2013
population_2013['Valeur'].sum(min_count=1)

7213211612.0

In [4]:
# importation de la table population pour 2017
population_2017 = pd.read_csv("population_2017.csv")

# 'Valeur' mise à la bonne unité
population_2017['Valeur'] = population_2017['Valeur']*1000

# calcul de la population mondiale de 2017
population_2017['Valeur'].sum(min_count=1)

8991167347.0

In [5]:
# le résultat ne semble pas cohérent, après obervation de la base de données suppression de l'individu Chine en 
# doublon
population_2017 = population_2017.loc[population_2017.Zone != 'Chine', :]

# calcul de la population mondiale de 2017
population_2017['Valeur'].sum(min_count=1)

7550036044.0

Parmi les documents sur les Bilans alimentaires que vous avez téléchargés, il y a des informations redondantes. En effet, certaines peuvent se calculer à partir d'autres : Production (Production) Importations (Import Quantity) Exportations (Export Quantity) Variation de stock (Stock Variation) Disponibilité intérieure (Domestic supply) Semences (Seed) Pertes (Waste) Nourriture (Food) , aussi appelée Disponibilité alimentaire (Food Supply) Aliments pour animaux (Feed) Traitement (Processing) Autres utilisations (Other uses)

# Question 2 :
Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique. C'est une équation à 3 termes de type a1+a2+[...]=b1+b2+[...]=c1+c2+[...] ) faisant intervenir chacune des 11 quantités données ci dessus. Illustrez cette équation avec l'exemple du blé en France

In [6]:
# importation de la table redondances (ne contient que les infos relatives au blé)
redondances = pd.read_csv("redondances.csv")

In [7]:
# attribution des quantités à 11 individus
a1 = 38614 # 'Production'
a2 = 21502 # 'Exportations - Quantité'
a3 = 2055 #  'Importations - Quantité'
a4 = 1131 #  'Variation de stock'
b1 = 20298 # 'Disponibilité intérieure'
c1 = 7822 # 'Aliments pour animaux'
c2 = 748 # 'Semences'
c3 = 358 # 'Pertes'
c4 = 1575 # 'Traitement'
c5 = 2824 # 'Autres Utilisations'
c6 = 6971 # 'Nourriture'

# vérification de a1+a2+[...]=b1+b2+[...]=c1+c2+[...]
a = a1 - a2 + a3 + a4
b = b1
c = c1 + c2 + c3 + c4 + c5 + c6
print(a, b, c)

20298 20298 20298

# Question 3 : 

Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines

Vous ferez cela à partir de ces informations : Population de chaque pays ; Disponibilité alimentaire ("Food Supply" en anglais) donnée pour chaque produit et pour chaque pays en kcal/personne/jour. Disponibilité alimentaire en protéines ("Protein supply quantity" en anglais) donnée pour chaque produit et pour chaque pays en g/personne/jour.

In [8]:
# importation de la table bilan_2013
bilan_2013 = pd.read_csv("bilan_2013.csv")

In [9]:
# formatage du dataframe principal
bilan_2013 = bilan_2013.pivot_table(values = ["Valeur"], index = ["Code Pays", "Pays", "Code Produit", "Produit", 
                                                                  "Année"],columns = ["Élément"], aggfunc = sum)
bilan_2013.columns = ['Aliments pour animaux', 'Autres Utilisations', 
                      'Disponibilité alimentaire (Kcal/personne/jour)', 
                      'Disponibilité alimentaire en quantité (kg/personne/an)', 
                      'Disponibilité de matière grasse en quantité (g/personne/jour)', 
                      'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 
                      'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 
                      'Population totale','Production', 'Semences', 'Traitement', 'Variation de stock']
bilan_2013 = bilan_2013.reset_index()
bilan_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Population totale,Production,Semences,Traitement,Variation de stock
0,1,Arménie,2501,Population,2013,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2977.0,NaN,NaN,NaN,NaN
1,1,Arménie,2511,Blé,2013,93.0,0.0,1024.0,130.60,3.6,...,554.0,1.0,361.0,389.0,32.0,NaN,312.0,30.0,10.0,-118.0
2,1,Arménie,2513,Orge,2013,137.0,26.0,0.0,0.00,0.0,...,198.0,0.0,9.0,0.0,15.0,NaN,189.0,14.0,7.0,0.0
3,1,Arménie,2514,Maïs,2013,96.0,NaN,0.0,0.03,NaN,...,102.0,NaN,82.0,0.0,7.0,NaN,21.0,0.0,NaN,NaN
4,1,Arménie,2515,Seigle,2013,1.0,NaN,1.0,0.12,0.0,...,1.0,NaN,0.0,0.0,0.0,NaN,1.0,0.0,NaN,0.0

In [10]:
# mise à l'unité utile des variables suivantes :
bilan_2013['Aliments pour animaux'] = bilan_2013['Aliments pour animaux']*1000000
bilan_2013['Autres Utilisations'] = bilan_2013['Autres Utilisations']*1000000
bilan_2013['Importations - Quantité'] = bilan_2013['Importations - Quantité']*1000000
bilan_2013['Exportations - Quantité'] = bilan_2013['Exportations - Quantité']*1000000
bilan_2013['Pertes'] = bilan_2013['Pertes']*1000000
bilan_2013['Production'] = bilan_2013['Production']*1000000
bilan_2013['Semences'] = bilan_2013['Semences']*1000000
bilan_2013['Traitement'] = bilan_2013['Traitement']*1000000
bilan_2013['Variation de stock'] = bilan_2013['Variation de stock']*1000000
bilan_2013['Disponibilité intérieure'] = bilan_2013['Disponibilité intérieure']*1000000
bilan_2013['Nourriture'] = bilan_2013['Nourriture']*1000000
bilan_2013['Population totale'] = bilan_2013['Population totale']*1000

In [11]:
# pour remplacer les valeurs 'NaN' par une valeur numérique
bilan_2013 = bilan_2013.fillna(0)

# pour obtenir une valeur sur chacune des lignes de la variable 'Population totale'
for elt in pd.unique(bilan_2013['Pays']):
    bilan_2013.loc[bilan_2013['Pays'] == elt,
                   'Population totale'] = bilan_2013.loc[bilan_2013['Pays'] == elt,'Population totale'].max()
    
# suppression de l'individu Chine en doublon
bilan_2013 = bilan_2013.loc[bilan_2013.Pays != 'Chine', :]

# pour supprimer la valeur 'Population' de l'ensemble de la variable 'Produit'
bilan_2013 = bilan_2013.loc[bilan_2013.Produit != 'Population', :]

In [12]:
# Calcul (pour chaque pays et chaque produit) de la disponibilité alimentaire en kcal

# création d'une nouvelle colonne résultante de la mutliplication de la colonne 
#'Disponibilité alimentaire (Kcal/personne/jour)' avec 'Population totale', le tout multiplié par le 
# nombre de jours, que compte une année
bilan_2013.loc[:, 'Dispo alim kcal (kcal/pays/an)'] = bilan_2013['Disponibilité alimentaire (Kcal/personne/jour)'] * bilan_2013['Population totale'] * 365

In [13]:
# Calcul (pour chaque pays et chaque produit) de la disponibilité alimentaire en kg de protéines

# création d'une nouvelle colonne résultante de la mutliplication de la colonne 
# 'Disponibilité de protéines en quantité (g/personne/jour)' avec'Population totale', le tout divisé par 
# 1000 (pour être à l'unité kg) et multiplié par le nombre de jours, que compte une année
a = bilan_2013['Disponibilité de protéines en quantité (g/personne/jour)'] * 365 / 1000
bilan_2013.loc[:, 'Dispo alim prot (kg/pays/an)'] = a * bilan_2013['Population totale']
bilan_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Importations - Quantité,Nourriture,Pertes,Population totale,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an)
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,361000000.0,389000000.0,32000000.0,2977000.0,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,9000000.0,0.0,15000000.0,2977000.0,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,82000000.0,0.0,7000000.0,2977000.0,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,0.0,0.0,0.0,2977000.0,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,1000000.0,1000000.0,0.0,2977000.0,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45

# Question 4 : 
A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg. Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la valeur calorique d'un oeuf.

Indication : La disponibilité alimentaire en kcal/personne/jour est calculée par la FAO en multipliant la quantité Nouriture (Food) par le ratio énergie/poids (en kcal/kg), puis en le divisant par la population du pays puis par 365. Ici, on vous demande juste de retrouver le ratio énergie/poids que la FAO a utilisé dans son calcul.

In [14]:
# Ratio "énergie/poids" (kcal/kg) = Disponibilité alimentaire (Kcal/personne/jour)*pop*365/Nourriture(en kg) 
# Ratio "énergie/poids" (kcal/kg) = Dispo alim (Kcal/pays/an)/Nourriture(en kg)

# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013.loc[:, 'Ratio "énergie/poids" (kcal/kg)'] = bilan_2013['Dispo alim kcal (kcal/pays/an)']/bilan_2013['Nourriture']
bilan_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Nourriture,Pertes,Population totale,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)"
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,389000000.0,32000000.0,2977000.0,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,0.0,15000000.0,2977000.0,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00,NaN
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,0.0,7000000.0,2977000.0,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05,NaN
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,0.0,0.0,2977000.0,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10,inf
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,1000000.0,0.0,2977000.0,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45,2173.210000

In [15]:
# à l'aide d'un nouveau dataframe sélection pour la variable 'Produit' de la valeur 'Oeufs'
bilan_2013_oeuf = bilan_2013[bilan_2013['Produit'] == "Oeufs"].copy()
bilan_2013_oeuf['Ratio "énergie/poids" (kcal/kg)'].mean()

inf

In [16]:
# pour remplacer les valeurs 'NaN' par une valeur numérique
bilan_2013 = bilan_2013.fillna(0)

# les valeurs 'inf' de la variable 'Ratio "énergie/poids" (kcal/kg)' sont remplacées par la valeur '0'
bilan_2013.loc[np.isinf(bilan_2013['Ratio "énergie/poids" (kcal/kg)']),'Ratio "énergie/poids" (kcal/kg)'] = 0

# on reprend la case [19]
bilan_2013_oeuf = bilan_2013[bilan_2013['Produit'] == "Oeufs"].copy()

# calcul de la moyenne sur l'ensemble des pays de la valeur 'Oeufs' au sein de la variable 
# 'Ratio "énergie/poids" (kcal/kg)'
# pour le calcul de la moyenne ne sont pris en compte, que les valeurs >0
bilan_2013_oeuf.loc[bilan_2013_oeuf['Ratio "énergie/poids" (kcal/kg)']>0,'Ratio "énergie/poids" (kcal/kg)'].mean()

1345.3003859252408

In [17]:
# après vérification sur la fiche Wikipédia de l'oeuf celui-ci à une valeur calorique de 1470 kcal/kg
# notre calcul nous donne 1345 kcal/kg

En suivant la même méthodologie, calculez également le pourcentage de protéïnes de chaque produit (pour chaque pays). Ce pourcentage est obtenu en calculant le ratio "poids de protéines/poids total" (attention aux unités utilisées). Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la teneur en protéines de l'avoine.

In [18]:
# Ratio "poids de protéines/poids total" (kg_prot/kg) = Dispo alim prot (kg/pays/an) / Nourriture(en kg)

# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013['Ratio "poids de protéines/poids total" (kg_prot/kg)'] = bilan_2013['Dispo alim prot (kg/pays/an)']/bilan_2013['Nourriture']

In [19]:
# à l'aide d'un nouveau dataframe sélection pour la variable 'Produit' de la valeur 'Avoine'
bilan_2013_avoine = bilan_2013[bilan_2013['Produit'] == "Avoine"].copy()

# calcul de la moyenne
bilan_2013_avoine['Ratio "poids de protéines/poids total" (kg_prot/kg)'].mean()

inf

In [20]:
# pour remplacer les valeurs 'NaN' par une valeur numérique
bilan_2013 = bilan_2013.fillna(0)

# les valeurs 'inf' de la variable 'Ratio "poids de protéines/poids total" kg_prot/kg' sont remplacées par la 
# valeur '0'
bilan_2013.loc[np.isinf(bilan_2013['Ratio "poids de protéines/poids total" (kg_prot/kg)']),'Ratio "poids de protéines/poids total" (kg_prot/kg)'] = 0

# on reprend la case [23]
bilan_2013_avoine = bilan_2013[bilan_2013['Produit'] == "Avoine"].copy()

# calcul de la moyenne sur l'ensemble des pays de la valeur 'Avoine' au sein de la variable 
# 'Ratio "poids de protéines/poids total" kg_prot/kg'
# pour le calcul de la moyenne ne sont pris en compte, que les valeurs >0
bilan_2013_avoine.loc[bilan_2013_avoine['Ratio "poids de protéines/poids total" (kg_prot/kg)']>0, 'Ratio "poids de protéines/poids total" (kg_prot/kg)'].mean()

0.08447081054780031

In [21]:
# après vérification sur la fiche Wikipédia de l'avoine celui-ci à un pourcentage de protéines de 10,7% 
# notre moyenne nous donne 8,44%

# Question 5 : 
Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids. 
Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne.
Citez 5 aliments parmi les 20 aliments les plus riches en protéines.

In [22]:
# création d'un nouveau dataframe où les lignes égales à 0 dans la variable 'Ratio kcal/kg' sont supprimées
bilan_2013_cal = bilan_2013.loc[bilan_2013['Ratio "énergie/poids" (kcal/kg)'] != 0, :]

In [23]:
# création d'un objet de type  DataFrameGroupBy, que nous appelons 'gb', celui-ci prend en attribut de 
# partitionnement la variable 'Produit' de la table 'bilan_2013_cal'
gb = bilan_2013_cal.groupby('Produit')

In [24]:
# sur cet objet gb, on peut ensuite appliquer la fonction d'agrégation .mean()
m = gb['Ratio "énergie/poids" (kcal/kg)',].mean()

# représentation du dataframe
groupped = pd.concat([m], axis=1)
groupped.columns = ['moy Ratio "énergie/poids" (kcal/kg)']

In [25]:
# tri descendant au sein du dataframe donnant les 20 aliments les plus caloriques
groupped.sort_values(by = 'moy Ratio "énergie/poids" (kcal/kg)', ascending = False)[0:20]

                          moy Ratio "énergie/poids" (kcal/kg)
Produit
Huiles de Foie de Poisso                          9982.932500
Huile de Sésame                                   9433.744729
Huile de Son de Riz                               9361.549883
Huiles de Poissons                                9003.715504
Huile d'Arachide                                  8935.765811
Huile d'Olive                                     8931.223447
Huile de Germe de Maïs                            8871.762566
Huil Plantes Oleif Autr                           8848.222893
Huile de Palmistes                                8789.540277
Huile Graines de Coton                            8750.320136
Huile de Palme                                    8719.419872
Huile de Tournesol                                8693.245772
Huile de Soja                                     8635.808245
Huile de Colza&Moutarde                           8627.372452
Huile de Coco                                     8565.739255
Graisses Animales Crue                            7583.862063
Beurre, Ghee                                      7331.424291
Palmistes                                         6496.635000
Sésame                                            5796.120413
Arachides Decortiquees                            5702.900100

Huiles de Foie de Poisson, Huile de Sésame, Huile de Son de Riz, Huiles de Poissons, Huile d'Olive

In [26]:
# création d'un nouveau dataframe où des lignes égales à 0 dans la variable 'Ratio kg_prot/kg' sont supprimées
bilan_2013_prot = bilan_2013.loc[bilan_2013['Ratio "poids de protéines/poids total" (kg_prot/kg)'] != 0, :]

In [27]:
# création d'un objet de type  DataFrameGroupBy, que nous appelons 'gb_1', celui-ci prend en attribut de 
# partitionnement la variable 'Produit' de la table 'bilan_2013_prot'
gb_1 = bilan_2013_prot.groupby('Produit')

In [28]:
# sur cet objet gb_1, on peut ensuite appliquer la fonction d'agrégation .mean()
m_1 = gb_1['Ratio "poids de protéines/poids total" (kg_prot/kg)',].mean()

# représentationdu dataframe
groupped_1 = pd.concat([m_1], axis=1)
groupped_1.columns = ['moy Ratio "poids de protéines/poids total" (kg_prot/kg)']

In [29]:
# tri descendant au sein du dataframe donnant les 20 aliments les plus riches en protéines
groupped_1.sort_values(by = 'moy Ratio "poids de protéines/poids total" (kg_prot/kg)', ascending = False)[0:20]

                          moy Ratio "poids de protéines/poids total" (kg_prot/kg)
Produit
Graines Colza/Moutarde                                             0.285365
Soja                                                               0.285331
Arachides Decortiquees                                             0.251466
Pois                                                               0.223244
Légumineuses Autres                                                0.219716
Haricots                                                           0.215452
Abats Comestible                                                   0.175610
Sésame                                                             0.175040
Viande, Autre                                                      0.174024
Plantes Oleiferes, Autre                                           0.170544
Aliments pour enfants                                              0.148832
Viande de Bovins                                                   0.143780
Cephalopodes                                                       0.139904
Viande d'Ovins/Caprins                                             0.135803
Viande de Volailles                                                0.126209
Piments                                                            0.121003
Poissons Pelagiques                                                0.119346
Graines de tournesol                                               0.111823
Poissons Marins, Autres                                            0.110133
Épices, Autres                                                     0.107418

Graines Colza/Moutarde, Soja, Arachides Decortiquees, Pois, Légumineuses Autres

# Question 6 : 
Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.

In [30]:
# importation de la table bilan_veg_2013 suite sélection 'végétaux' dans 'groupe de produit' lors du téléchargement
# de la BDD
bilan_veg_2013 = pd.read_csv("bilan_veg_2013.csv")

In [31]:
# utilisation d'une méthode différente de la 'Question 5'

# création de la variable list_veg ne contenant que les 'Codes Produits' des végétaux
list_veg = np.unique(bilan_veg_2013['Code Produit'])

# nous appliquons cette liste à 'bilan_2013'
bilan_2013_veg = bilan_2013.loc[bilan_2013['Code Produit'].isin(list_veg),:].copy()

In [32]:
# disponibilité intérieure mondiale pour chaque produit exprimée en kcal 
# = disponibilité intérieure * Ratio kcal/kg
# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013_veg['Dispo intér Kcal'] = bilan_2013_veg['Disponibilité intérieure']*bilan_2013_veg['Ratio "énergie/poids" (kcal/kg)']

In [33]:
# Calcul, pour l'année 2013, pour les produits végétaux uniquement, de la disponibilité intérieure mondiale 
# exprimée en kcal.
bilan_2013_veg['Dispo intér Kcal'].sum(min_count=1)

1.2312091265143276e+16

# Question 7 : 
Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [34]:
# Suivant des recherches sur internet, un individu moyen a besoin de 2 500 Kcal par jour

In [35]:
# Calcul du nombre d'humains nourris en terme de calories si toute la disponibilité intérieure mondiale de produits 
# végétaux était utilisée pour de la nourriture 
bilan_2013_veg['Dispo intér Kcal'].sum(min_count=1) / (2500*365)

13492702756.321398

In [36]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013_veg['Dispo intér Kcal'].sum(min_count=1) / (2500*365) / 7213211612.0

1.8705541279108946

In [37]:
# ce qui amène à dire, que si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour 
# de la nourriture, elle répondrait aux besoins en kcal de 1,87 fois la population mondiale

In [38]:
# Suivant des recherches sur internet, un individu moyen a besoin de 70g de protéines par jour

In [39]:
# disponibilité intérieure mondiale pour chaque produit exprimée en protéines
# = disponibilité intérieure * Ratio kg_prot/kg
# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013_veg['Dispo intér prot'] = bilan_2013_veg['Disponibilité intérieure']*bilan_2013_veg['Ratio "poids de protéines/poids total" (kg_prot/kg)']

In [40]:
# Calcul du nombre d'humains nourris en terme de protéines si toute la disponibilité intérieure mondiale de 
# produits végétaux était utilisée pour de la nourriture 
bilan_2013_veg['Dispo intér prot'].sum(min_count=1) / ((70/1000)*365)

11357234212.99942

In [41]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013_veg['Dispo intér prot'].sum(min_count=1) / ((70/1000)*365) / 7213211612.0

1.5745045097672397

In [42]:
# ce qui amène à dire, que si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour 
# de la nourriture, elle répondrait aux besoins en protéines de 1,57 fois la population mondiale

# Question 8 : 
Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux (Food) la nourriture végétale destinée aux animaux (Feed) et les pertes de produits végétaux (Waste) étaient utilisés pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [43]:
# Food + Feed + Waste  = Nourriture + Aliments pour animaux + Pertes

# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013_veg['Food_Feed_Waste'] = bilan_2013_veg['Nourriture']+bilan_2013_veg['Aliments pour animaux']+bilan_2013_veg['Pertes']

In [44]:
# Food + Feed + Waste exprimés pour chaque produit en kcal = (Food + Feed + Waste) * Ratio NRJ/Pds

# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013_veg['Food_Feed_Waste_kcal'] = bilan_2013_veg['Food_Feed_Waste']*bilan_2013_veg['Ratio "énergie/poids" (kcal/kg)']

In [45]:
# Calcul, pour l'année 2013, pour les produits végétaux uniquement, de la Food + Feed + Waste mondiale 
# exprimés en kcal.
bilan_2013_veg['Food_Feed_Waste_kcal'].sum(min_count=1)

9173263648969462.0

In [46]:
# Calcul du nombre d'humains nourris en terme de calories  
bilan_2013_veg['Food_Feed_Waste_kcal'].sum(min_count=1) / (2500*365)

10052891670.10352

In [47]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013_veg['Food_Feed_Waste_kcal'].sum(min_count=1) / (2500*365) / 7213211612.0

1.3936776308322063

In [48]:
# ce qui amène à dire, que si tous les Food + Feed + Waste étaient utilisés pour de la nourriture, ils répondraient
# aux besoins en kcal d'1,39 fois la population mondiale

In [49]:
# Food + Feed + Waste exprimés pour chaque produit en protéines = (Food + Feed + Waste) * Ratio kg_prot/kg

# création d'une nouvelle colonne résultante de l'égalité donnée ci-dessus
bilan_2013_veg['Food_Feed_Waste_prot'] = bilan_2013_veg['Food_Feed_Waste']*bilan_2013_veg['Ratio "poids de protéines/poids total" (kg_prot/kg)']

In [50]:
# Calcul, pour l'année 2013, pour les produits végétaux uniquement, de la Food + Feed + Waste mondiale 
# exprimés en protéines.
bilan_2013_veg['Food_Feed_Waste_prot'].sum(min_count=1)

203583064770.38016

In [51]:
# Calcul du nombre d'humains nourris en terme de protéines si toute la disponibilité Food + Feed + Waste de 
# produits végétaux était utilisée pour de la nourriture 
bilan_2013_veg['Food_Feed_Waste_prot'].sum(min_count=1) / ((70/1000)*365)

7968026018.410182

In [52]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013_veg['Food_Feed_Waste_prot'].sum(min_count=1) / ((70/1000)*365) / 7213211612.0

1.1046433193717016

In [53]:
# ce qui amène à dire, que si tous les Food + Feed + Waste étaient utilisés pour de la nourriture, ils répondraient
# aux besoins en protéines de plus d'1,10 fois la population mondiale

# Question 9 : 
Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [54]:
# pour rappel
# Suivant des recherches sur internet, un individu moyen a besoin de 2 500 Kcal par jour

In [55]:
# somme de de la colonne 'Dispo alim (kcal/pays/an)'
bilan_2013['Dispo alim kcal (kcal/pays/an)'].sum(min_count=1)

7363883420185000.0

In [56]:
# nombre d'humains nourris
bilan_2013['Dispo alim kcal (kcal/pays/an)'].sum(min_count=1) / (2500*365)

8070009227.6

In [57]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013['Dispo alim kcal (kcal/pays/an)'].sum(min_count=1) / (2500*365) / 7213211612.0

1.1187817107950389

In [58]:
# ce qui amène à dire, que la disponibilité alimentaire mondiale répondrait aux besoins en kcal d'1,12 fois la 
# population mondiale

In [59]:
# pour rappel
# Suivant des recherches sur internet, un individu moyen a besoin de 70g de protéines par jour

In [60]:
# somme de de la colonne 'Dispo alim prot (kg/pays/an)'
bilan_2013['Dispo alim prot (kg/pays/an)'].sum(min_count=1)

207259180075.55

In [61]:
# Calcul du nombre d'humains nourris  
bilan_2013['Dispo alim prot (kg/pays/an)'].sum(min_count=1) / ((70/1000)*365)

8111905286.714285

In [62]:
# Résultat donné en pourcentage de la population mondiale
bilan_2013['Dispo alim prot (kg/pays/an)'].sum(min_count=1) / ((70/1000)*365) / 7213211612.0

1.1245899500881418

In [63]:
# ce qui amène à dire, que la disponibilité alimentaire mondiale répondrait aux besoins en protéines d'1,12 fois la 
# population mondiale

# Question 10 : 
A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO.

Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

In [64]:
# importation de la table securite_2013
securite_2013 = pd.read_csv("securite_2013.csv")

In [65]:
# vérification de la présence de la Chine en doublon
securite_2013.iloc[36:43,:]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
36,FS,Données de la sécurité alimentaire,40,Chili,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,0.6,F,Estimation FAO
37,FS,Données de la sécurité alimentaire,351,Chine,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,137.3,F,Estimation FAO
38,FS,Données de la sécurité alimentaire,96,Chine - RAS de Hong-Kong,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,<0.2,Moins de 200 000 personnes sont sous-alimentées
39,FS,Données de la sécurité alimentaire,128,Chine - RAS de Macao,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,<0.1,Moins de 100 000 personnes sont sous-alimentées
40,FS,Données de la sécurité alimentaire,41,"Chine, continentale",6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,136.2,F,Estimation FAO
41,FS,Données de la sécurité alimentaire,214,"Chine, Taiwan Province de",6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,1.0,F,Estimation FAO
42,FS,Données de la sécurité alimentaire,50,Chypre,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,<0.1,Moins de 100 000 personnes sont sous-alimentées

In [66]:
# suppression de l'individu Chine en doublon
securite_2013 = securite_2013.loc[securite_2013.Zone != 'Chine', :]

In [67]:
# pour remplacer les valeurs 'NaN' par une valeur numérique
securite_2013 = securite_2013.fillna(0)

# mise à l'unité utile de la variable suivante
securite_2013['Valeur'] = securite_2013['Valeur']*1000000

# calcul du nombre de personne considéré comme étant en sous-nutrition
securite_2013['Valeur'].sum(min_count=1)

739700000.0

In [68]:
# Résultat donné en pourcentage de la population mondiale
securite_2013['Valeur'].sum(min_count=1) / 7213211612.0

0.10254794116526746

In [69]:
# ce qui amène à dire, que pour l'année 2013, 10% de la population mondiale est considérée comme étant en 
# sous-nutrition

In [70]:
# importation de la table securite_2016
securite_2016 = pd.read_csv("securite_2016.csv")

In [71]:
# suppression de l'individu Chine en doublon
securite_2016 = securite_2016.loc[securite_2016.Zone != 'Chine', :]

In [72]:
# pour remplacer les valeurs 'NaN' par une valeur numérique
securite_2016 = securite_2016.fillna(0)

# mise à l'unité utile de la variable suivante
securite_2016['Valeur'] = securite_2016['Valeur']*1000000

# calcul du nombre de personne considéré comme étant en sous-nutrition
securite_2016['Valeur'].sum(min_count=1)

743700000.0

In [73]:
# Résultat donné en pourcentage de la population mondiale
securite_2016['Valeur'].sum(min_count=1) / 7550036044.0

0.09850284100180118

In [74]:
# ce qui amène à dire, que pour l'année 2016, 9,85% de la population mondiale est considérée comme étant en 
# sous-nutrition

In [75]:
# Afin d'établir la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO
# importation de la table cereales_2013
bil_alim_cereales_2013 = pd.read_csv("bil_alim_cereales_2013.csv")

In [76]:
# tri ascendant  sur la variable 'Code Produit' au sein du dataframe 
(bil_alim_cereales_2013[['Code Produit', 'Produit']]).sort_values(by = 'Code Produit').head()

       Code Produit Produit
0              2511     Blé
10736          2511     Blé
10735          2511     Blé
10734          2511     Blé
10733          2511     Blé

In [77]:
# suppression des doublons au sein du dataframe sur la variable 'Code Produit'
b = (bil_alim_cereales_2013[['Code Produit', 'Produit']]).sort_values(by = 'Code Produit').drop_duplicates('Code Produit')
b

       Code Produit           Produit
0              2511               Blé
14461          2513              Orge
15510          2514              Maïs
9919           2515            Seigle
14596          2516            Avoine
12660          2517            Millet
11280          2518            Sorgho
12800          2520  Céréales, Autres
4530           2805  Riz (Eq Blanchi)

In [78]:
# Afin de repérer dans nos données les informations concernant les céréales  
# création liste 'list_cer'
list_cer = np.unique(bil_alim_cereales_2013['Code Produit'])

In [79]:
# création d'une nouvelle colonne affichant si le 'Code Produit' fait parti des créréales données par la FAO ou non
bilan_2013['is_cereal'] = bilan_2013['Code Produit'].isin(list_cer)

In [80]:
bilan_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Population totale,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,2977000.0,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946,0.085252,True
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,2977000.0,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00,0.000000,0.000000,True
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,2977000.0,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05,0.000000,0.000000,True
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,2977000.0,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10,0.000000,0.000000,True
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,2977000.0,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45,2173.210000,0.097794,True

# Question 11 : 
En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition, pour une année choisie.

Repérez les 15 produits les plus exportés par ce groupe de pays sur l'année choisie.

Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné sur l'année choisie)

Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits. Ensuite, calculez pour chaque produit les 2 quantités suivantes :

le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.
le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

In [81]:
# création d'une nouvelle table où ne seront conservées que les céréales destinées à l'alimentation (humaine et 
# animale)
cer_alim_ani_2013 = bilan_2013.loc[bilan_2013['is_cereal'] == 1, :]
cer_alim_ani_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Population totale,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,2977000.0,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946,0.085252,True
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,2977000.0,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00,0.000000,0.000000,True
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,2977000.0,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05,0.000000,0.000000,True
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,2977000.0,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10,0.000000,0.000000,True
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,2977000.0,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45,2173.210000,0.097794,True

In [82]:
# calcul de la  proportion (en termes de poids) destinée à l'alimentation animale
cer_alim_ani_2013['Aliments pour animaux'].sum(min_count=1)/((cer_alim_ani_2013['Aliments pour animaux'].sum(min_count=1))+cer_alim_ani_2013['Nourriture'].sum(min_count=1))

0.45914025686646043

In [83]:
# ce qui amène à dire, que pour l'année 2013, 46% de la production mondiale des céréales destinées à 
# l'alimentation (humaine et animale) est destinée à l'alimentation animale

In [84]:
# Afin de repérer dans nos données les informations concernant les pays dans lesquels la FAO recense des personnes 
# en sous-nutrition
# création liste 'list_sous_nut' des pays en sous-nutrition
list_sous_nut = np.unique(securite_2013.loc[securite_2013['Valeur']>0,'Code zone'])

In [85]:
# création d'une nouvelle colonne affichant si le 'Code Pays' fait parti des pays donnés par la FAO ou non
bilan_2013['is_ss_nut'] = bilan_2013['Code Pays'].isin(list_sous_nut)

In [86]:
bilan_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946,0.085252,True,True
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00,0.000000,0.000000,True,True
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05,0.000000,0.000000,True,True
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10,0.000000,0.000000,True,True
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45,2173.210000,0.097794,True,True

In [87]:
# création d'une nouvelle table où ne seront conservés que les pays donnés par la FAO
ss_nut_2013 = bilan_2013.loc[bilan_2013['is_ss_nut'] == 1, :]
ss_nut_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.60,...,312000000.0,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946,0.085252,True,True
2,1,Arménie,2513,Orge,2013,137000000.0,26000000.0,0.0,0.00,0.00,...,189000000.0,14000000.0,7000000.0,0.0,0.000000e+00,0.00,0.000000,0.000000,True,True
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.00,...,21000000.0,0.0,0.0,0.0,0.000000e+00,10866.05,0.000000,0.000000,True,True
4,1,Arménie,2515,Seigle,2013,1000000.0,0.0,1.0,0.12,0.00,...,1000000.0,0.0,0.0,0.0,1.086605e+09,21732.10,0.000000,0.000000,True,True
5,1,Arménie,2516,Avoine,2013,4000000.0,0.0,2.0,0.37,0.03,...,5000000.0,0.0,0.0,0.0,2.173210e+09,97794.45,2173.210000,0.097794,True,True

In [88]:
# pour repérer les 15 produits les plus exportés par ce groupe de pays sur 2013
# création d'un objet de type  DataFrameGroupBy, que nous appelons  gb_2 :
gb_2 = ss_nut_2013.groupby('Code Produit')

In [89]:
# sur cet objet gb_2, on peut ensuite appliquer la fonction d'agrégation .sum()
s_2 = gb_2['Exportations - Quantité',].sum()

# représentation du dataframe
groupped_2 = pd.concat([s_2], axis=1)
groupped_2.columns = ["Exportations - Quantité"]

In [90]:
# tri descendant au sein du dataframe 
c = groupped_2.sort_values(by = 'Exportations - Quantité', ascending = False)[0:15]
c

              Exportations - Quantité
Code Produit
2577                     4.628500e+10
2514                     3.788800e+10
2532                     3.584300e+10
2805                     3.278700e+10
2542                     2.523700e+10
2511                     2.484100e+10
2605                     1.994800e+10
2615                     1.780500e+10
2625                     1.459000e+10
2848                     1.448600e+10
2555                     1.438900e+10
2763                     1.368000e+10
2601                     8.901000e+09
2617                     7.786000e+09
2611                     6.838000e+09

In [91]:
# Afin de repérer dans nos données les informations concernant les produits les plus exportés par les pays en 
# sous-nutrition
# création liste 'list_prod_exp_ss_nut'
list_prod_exp_ss_nut = np.unique(c.index)

In [92]:
# création d'une nouvelle colonne affichant si le 'Code Produit' fait parti de la liste ci-dessus ou non
bilan_2013['is_prod_exp_ss_nut'] = bilan_2013['Code Produit'].isin(list_prod_exp_ss_nut)

In [93]:
# création d'une nouvelle table où ne seront conservées que les pays donnés ci-dessus
exp_ss_nut_2013 = bilan_2013.loc[bilan_2013['is_prod_exp_ss_nut'] == 1, :]
exp_ss_nut_2013.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut,is_prod_exp_ss_nut
1,1,Arménie,2511,Blé,2013,93000000.0,0.0,1024.0,130.60,3.6,...,30000000.0,10000000.0,-118000000.0,1.112684e+12,33163184.60,2860.368946,0.085252,True,True,True
3,1,Arménie,2514,Maïs,2013,96000000.0,0.0,0.0,0.03,0.0,...,0.0,0.0,0.0,0.000000e+00,10866.05,0.000000,0.000000,True,True,True
10,1,Arménie,2532,Manioc,2013,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.000000e+00,0.00,0.000000,0.000000,False,True,True
13,1,Arménie,2542,Sucre Eq Brut,2013,0.0,0.0,302.0,33.03,0.0,...,0.0,0.0,3000000.0,3.281547e+11,0.00,3348.517449,0.000000,False,True,True
19,1,Arménie,2555,Soja,2013,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.000000e+00,0.00,0.000000,0.000000,False,True,True

In [94]:
# tri descendant au sein du dataframe 
exp_ss_nut_2013.sort_values(by = 'Importations - Quantité', ascending = False)[0:200]

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut,is_prod_exp_ss_nut
2538,41,"Chine, continentale",2555,Soja,2013,9.530000e+09,0.000000e+00,35.0,3.66,1.18,...,7.130000e+08,5.916200e+10,0.000000e+00,1.770062e+13,1.663858e+09,3489.869563,0.328048,False,True,True
2525,41,"Chine, continentale",2532,Manioc,2013,2.286800e+10,7.940000e+09,6.0,1.91,0.01,...,0.000000e+00,0.000000e+00,0.000000e+00,3.034392e+12,2.528660e+07,1147.218045,0.009560,False,True,True
7043,110,Japon,2514,Maïs,2013,1.096400e+10,2.880000e+08,61.0,9.21,0.20,...,0.000000e+00,2.235000e+09,2.590000e+08,2.830861e+12,7.425210e+06,2417.473237,0.006341,True,False,True
3716,59,Égypte,2511,Blé,2013,4.860000e+09,0.000000e+00,1175.0,146.83,6.27,...,2.170000e+08,0.000000e+00,-2.600000e+08,3.519177e+13,1.066835e+09,2920.963396,0.088549,True,True,True
7574,117,République de Corée,2514,Maïs,2013,6.281000e+09,4.700000e+07,82.0,12.46,0.17,...,1.000000e+06,1.631000e+09,0.000000e+00,1.474442e+12,8.091448e+06,2401.370668,0.013178,True,False,True
6137,100,Inde,2577,Huile de Palme,2013,0.000000e+00,6.782000e+09,31.0,1.30,3.54,...,0.000000e+00,0.000000e+00,-1.200000e+07,1.416796e+13,0.000000e+00,8686.673268,0.000000,False,True,True
4822,79,Allemagne,2848,Lait - Excl Beurre,2013,2.064000e+09,5.040000e+08,331.0,258.70,16.50,...,0.000000e+00,0.000000e+00,0.000000e+00,9.994663e+12,7.422018e+08,467.018481,0.034681,False,False,True
2610,41,"Chine, continentale",2848,Lait - Excl Beurre,2013,1.608000e+09,0.000000e+00,58.0,32.66,3.22,...,0.000000e+00,0.000000e+00,0.000000e+00,2.933245e+13,1.552597e+09,648.202364,0.034310,False,True,True
6755,106,Italie,2848,Lait - Excl Beurre,2013,5.240000e+08,3.010000e+08,272.0,246.88,18.27,...,0.000000e+00,0.000000e+00,0.000000e+00,6.055087e+12,3.800012e+08,402.144332,0.025238,False,False,True
1349,21,Brésil,2511,Blé,2013,6.000000e+08,1.000000e+06,384.0,53.00,1.14,...,2.310000e+08,0.000000e+00,0.000000e+00,2.808274e+13,7.459477e+08,2644.325605,0.070240,True,False,True
9068,138,Mexique,2514,Maïs,2013,1.261500e+10,3.000000e+07,986.0,116.34,10.93,...,3.700000e+08,1.602000e+09,2.500000e+09,4.402606e+13,1.134586e+09,3093.455838,0.079721,True,True,True
6197,101,Indonésie,2511,Blé,2013,2.020000e+08,1.550000e+08,183.0,25.45,0.51,...,0.000000e+00,0.000000e+00,0.000000e+00,1.668980e+13,4.459733e+08,2624.182307,0.070122,True,True,True
14468,231,États-Unis d'Amérique,2605,"Légumes, Autres",2013,1.930000e+08,0.000000e+00,43.0,66.66,0.40,...,0.000000e+00,0.000000e+00,0.000000e+00,5.023200e+12,2.383100e+08,235.455163,0.011170,False,False,True
2554,41,"Chine, continentale",2577,Huile de Palme,2013,0.000000e+00,4.304000e+09,45.0,1.86,5.11,...,0.000000e+00,0.000000e+00,0.000000e+00,2.275794e+13,0.000000e+00,8814.073577,0.000000,False,True,True
2600,41,"Chine, continentale",2763,Poissons Pelagiques,2013,8.634000e+09,0.000000e+00,1.0,0.31,0.03,...,0.000000e+00,0.000000e+00,0.000000e+00,5.057320e+11,5.057320e+07,1173.392007,0.117339,False,True,True
7041,110,Japon,2511,Blé,2013,1.156000e+09,6.200000e+07,387.0,45.04,1.69,...,2.000000e+07,1.520000e+08,1.950000e+08,1.795973e+13,4.965609e+08,3135.974458,0.086705,True,False,True
246,4,Algérie,2511,Blé,2013,5.450000e+08,8.200000e+08,1424.0,185.42,5.34,...,1.530000e+08,0.000000e+00,-1.800000e+08,2.037875e+13,6.149402e+08,2803.129309,0.084586,True,True,True
6661,106,Italie,2511,Blé,2013,1.680000e+09,7.000000e+06,1041.0,146.37,3.85,...,3.250000e+08,7.500000e+07,1.054000e+09,2.317407e+13,7.301723e+08,2595.952207,0.081794,True,False,True
14328,229,Royaume-Uni,2848,Lait - Excl Beurre,2013,1.374000e+09,8.050000e+08,341.0,232.20,21.33,...,0.000000e+00,1.080000e+08,0.000000e+00,7.889090e+12,4.407248e+08,536.016413,0.029945,False,False,True
3718,59,Égypte,2514,Maïs,2013,7.032000e+09,2.820000e+08,596.0,62.42,8.36,...,3.200000e+07,1.480000e+08,0.000000e+00,1.785046e+13,4.708209e+08,3485.057056,0.091921,True,True,True
12705,203,Espagne,2514,Maïs,2013,9.120000e+09,1.085000e+09,15.0,1.99,0.05,...,2.000000e+07,8.400000e+07,1.540000e+08,2.569253e+11,5.823641e+06,2762.637903,0.062620,True,False,True
2516,41,"Chine, continentale",2511,Blé,2013,2.662800e+10,2.929000e+09,549.0,63.36,2.92,...,4.600000e+09,3.160000e+08,-1.783000e+09,2.776468e+14,8.865481e+09,3162.877132,0.100993,True,True,True
14423,231,États-Unis d'Amérique,2511,Blé,2013,6.196000e+09,1.600000e+07,599.0,80.43,2.85,...,2.096000e+09,0.000000e+00,5.284000e+09,6.997435e+13,2.260440e+09,2718.295019,0.087811,True,False,True
4729,79,Allemagne,2511,Blé,2013,7.494000e+09,7.740000e+08,654.0,83.41,2.59,...,5.710000e+08,9.000000e+07,-3.079000e+09,1.974776e+13,6.392357e+08,2861.994517,0.092643,True,False,True
9758,150,Pays-Bas,2611,"Oranges, Mandarines",2013,0.000000e+00,0.000000e+00,53.0,87.35,0.17,...,0.000000e+00,0.000000e+00,-1.500000e+08,3.242029e+11,5.321820e+06,221.450038,0.003635,False,False,True
14516,231,États-Unis d'Amérique,2848,Lait - Excl Beurre,2013,4.810000e+08,5.972000e+09,368.0,254.69,22.15,...,0.000000e+00,0.000000e+00,2.210000e+09,4.298925e+13,2.563000e+09,527.391340,0.031443,False,False,True
9805,150,Pays-Bas,2848,Lait - Excl Beurre,2013,5.990000e+08,0.000000e+00,460.0,341.47,27.66,...,0.000000e+00,0.000000e+00,-6.080000e+08,2.813836e+12,1.767211e+08,491.671518,0.030879,False,False,True
11811,185,Fédération de Russie,2848,Lait - Excl Beurre,2013,1.066300e+10,9.740000e+08,269.0,163.57,15.28,...,0.000000e+00,0.000000e+00,0.000000e+00,1.402416e+13,8.456201e+08,600.246374,0.036193,False,False,True
7572,117,République de Corée,2511,Blé,2013,1.900000e+09,0.000000e+00,392.0,50.84,1.56,...,1.000000e+06,0.000000e+00,-3.860000e+08,7.048550e+12,2.015670e+08,2813.792431,0.080466,True,False,True
9712,150,Pays-Bas,2511,Blé,2013,2.900000e+09,6.560000e+08,558.0,70.17,2.57,...,9.800000e+07,4.200000e+07,1.780000e+08,3.413306e+12,1.093726e+08,2902.470689,0.093004,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14444,231,États-Unis d'Amérique,2555,Soja,2013,2.240000e+09,0.000000e+00,0.0,0.04,0.00,...,2.640000e+09,4.718900e+10,-8.000000e+08,0.000000e+00,2.336372e+06,0.000000,0.194698,False,False,True
13494,216,Thaïlande,2532,Manioc,2013,1.800000e+09,2.081000e+09,40.0,13.00,0.05,...,0.000000e+00,0.000000e+00,0.000000e+00,9.783606e+11,3.424262e+06,1123.261309,0.003931,False,True,True
4812,79,Allemagne,2763,Poissons Pelagiques,2013,4.000000e+06,0.000000e+00,7.0,2.46,0.37,...,0.000000e+00,0.000000e+00,1.800000e+07,2.113675e+11,2.355238e+07,1036.115123,0.115453,False,False,True
13578,216,Thaïlande,2848,Lait - Excl Beurre,2013,0.000000e+00,1.470000e+08,45.0,29.35,1.74,...,0.000000e+00,0.000000e+00,1.100000e+07,1.100656e+12,6.016918e+07,559.560587,0.030589,False,True,True
2001,33,Canada,2542,Sucre Eq Brut,2013,0.000000e+00,0.000000e+00,333.0,32.29,0.00,...,0.000000e+00,0.000000e+00,0.000000e+00,4.276196e+12,0.000000e+00,3764.257210,0.000000,False,False,True
12237,194,Arabie saoudite,2805,Riz (Eq Blanchi),2013,4.000000e+06,1.400000e+07,385.0,36.02,0.74,...,0.000000e+00,0.000000e+00,-1.550000e+08,4.051195e+12,7.744623e+07,3899.129187,0.074539,True,True,True
12740,203,Espagne,2577,Huile de Palme,2013,0.000000e+00,7.990000e+08,0.0,0.00,0.00,...,0.000000e+00,0.000000e+00,-2.500000e+08,0.000000e+00,0.000000e+00,0.000000,0.000000,False,False,True
2042,33,Canada,2625,"Fruits, Autres",2013,0.000000e+00,0.000000e+00,40.0,32.87,0.75,...,0.000000e+00,0.000000e+00,1.000000e+06,5.136572e+11,6.677544e+06,444.340138,0.005776,False,False,True
10531,162,Norvège,2763,Poissons Pelagiques,2013,1.251000e+09,0.000000e+00,14.0,4.85,0.67,...,0.000000e+00,0.000000e+00,1.240000e+08,2.576973e+10,3.184402e+06,1073.738750,0.132683,False,False,True
13972,223,Turquie,2555,Soja,2013,0.000000e+00,0.000000e+00,4.0,1.71,0.15,...,3.000000e+06,1.160000e+09,0.000000e+00,1.094022e+11,9.572691e+06,854.704531,0.074787,False,False,True
14135,225,Émirats arabes unis,2805,Riz (Eq Blanchi),2013,2.000000e+06,1.500000e+08,555.0,56.25,1.08,...,0.000000e+00,0.000000e+00,-5.100000e+07,1.893266e+12,3.523863e+07,3599.364924,0.066994,True,True,True
4781,79,Allemagne,2617,Pommes,2013,0.000000e+00,0.000000e+00,25.0,18.65,0.20,...,0.000000e+00,9.000000e+07,2.090000e+08,7.548839e+11,4.529303e+06,489.231286,0.002935,False,False,True
92,2,Afghanistan,2511,Blé,2013,0.000000e+00,0.000000e+00,1369.0,160.23,4.69,...,3.220000e+08,0.000000e+00,-3.500000e+08,1.526638e+13,4.116011e+08,3118.769381,0.084086,True,True,True
3808,59,Égypte,2848,Lait - Excl Beurre,2013,8.920000e+08,5.100000e+07,94.0,59.46,5.92,...,0.000000e+00,4.700000e+07,0.000000e+00,2.815341e+12,1.695195e+08,577.032457,0.034745,False,True,True
11740,185,Fédération de Russie,2555,Soja,2013,6.000000e+08,0.000000e+00,0.0,0.05,0.00,...,1.400000e+08,1.930000e+09,0.000000e+00,0.000000e+00,1.042688e+06,0.000000,0.148955,False,False,True
8550,131,Malaisie,2577,Huile de Palme,2013,0.000000e+00,3.930000e+08,164.0,6.89,18.54,...,0.000000e+00,0.000000e+00,-4.000000e+07,1.778860e+12,1.084671e+05,8677.364000,0.000529,False,True,True
2424,40,Chili,2514,Maïs,2013,1.920000e+09,2.390000e+08,198.0,21.04,2.35,...,2.000000e+06,0.000000e+00,0.000000e+00,1.273397e+12,3.312120e+07,3432.338005,0.089275,True,True,True
14285,229,Royaume-Uni,2615,Bananes,2013,0.000000e+00,0.000000e+00,28.0,16.58,0.05,...,0.000000e+00,0.000000e+00,0.000000e+00,6.477845e+11,8.328658e+06,616.350599,0.007925,False,False,True
4234,68,France,2601,Tomates,2013,0.000000e+00,0.000000e+00,10.0,20.45,0.11,...,0.000000e+00,0.000000e+00,0.000000e+00,2.346622e+11,1.173311e+07,178.450304,0.008923,False,False,True
796,11,Autriche,2848,Lait - Excl Beurre,2013,3.050000e+08,6.300000e+07,269.0,258.09,15.48,...,0.000000e+00,0.000000e+00,-5.500000e+07,8.340816e+11,6.892801e+07,380.511667,0.031445,False,False,True
12331,195,Sénégal,2805,Riz (Eq Blanchi),2013,0.000000e+00,6.300000e+07,715.0,72.29,1.36,...,6.000000e+06,1.000000e+06,-2.140000e+08,3.688360e+12,7.433463e+07,3608.962500,0.072734,True,True,True
7593,117,République de Corée,2555,Soja,2013,3.000000e+07,0.000000e+00,66.0,8.35,2.80,...,4.000000e+06,8.140000e+08,0.000000e+00,1.186746e+12,1.087850e+08,2887.459051,0.264684,False,False,True
7618,117,République de Corée,2605,"Légumes, Autres",2013,0.000000e+00,0.000000e+00,140.0,172.38,1.33,...,0.000000e+00,0.000000e+00,0.000000e+00,2.517339e+12,1.312613e+08,296.436564,0.015457,False,False,True
6206,101,Indonésie,2532,Manioc,2013,4.800000e+08,8.894000e+09,132.0,46.97,0.30,...,0.000000e+00,0.000000e+00,0.000000e+00,1.203854e+13,6.384076e+07,1025.866543,0.005440,False,True,True
7321,114,Kenya,2511,Blé,2013,0.000000e+00,3.400000e+07,258.0,34.65,1.11,...,1.100000e+07,0.000000e+00,5.000000e+07,4.176816e+12,1.251426e+08,2717.512154,0.081420,True,True,True
8605,131,Malaisie,2805,Riz (Eq Blanchi),2013,5.200000e+07,2.710000e+08,762.0,81.25,1.72,...,1.300000e+07,0.000000e+00,1.080000e+08,8.265189e+12,1.466475e+08,3422.438596,0.060724,True,True,True
6707,106,Italie,2605,"Légumes, Autres",2013,5.520000e+08,0.000000e+00,66.0,96.43,0.51,...,1.400000e+07,0.000000e+00,0.000000e+00,1.469249e+12,8.058609e+07,249.829808,0.013703,False,False,True
14962,237,Viet Nam,2848,Lait - Excl Beurre,2013,0.000000e+00,0.000000e+00,27.0,16.36,0.88,...,0.000000e+00,0.000000e+00,0.000000e+00,9.035064e+11,5.521428e+07,602.337600,0.036810,False,True,True
11115,173,Pologne,2511,Blé,2013,2.600000e+09,6.500000e+08,877.0,108.83,3.20,...,6.000000e+08,2.400000e+07,2.600000e+08,1.223345e+13,3.861140e+08,2941.440920,0.092838,True,False,True
1988,33,Canada,2514,Maïs,2013,1.072300e+10,2.490000e+08,113.0,18.95,0.37,...,1.600000e+07,1.176000e+09,0.000000e+00,1.451082e+12,3.158992e+07,2175.534618,0.047361,True,False,True

In [95]:
# nous allons grouper ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 
# produits
# création d'un objet de type  DataFrameGroupBy, que nous appelons  gb_3 :
gb_3 = exp_ss_nut_2013.sort_values(by = 'Importations - Quantité', ascending = False)[0:200].groupby('Produit')

In [96]:
# sur cet objet gb_3, on peut ensuite appliquer la fonction d'agrégation .sum()
s_3 = gb_3[['Importations - Quantité', 'Autres Utilisations', 'Disponibilité intérieure', 'Aliments pour animaux',
           'Nourriture']].sum()
s_3

,Importations - Quantité,Autres Utilisations,Disponibilité intérieure,Aliments pour animaux,Nourriture
Produit,,,,,
Bananes,9.663000e+09,0.000000e+00,7.466000e+09,0.000000e+00,7.123000e+09
Blé,1.475760e+11,1.504700e+10,4.564750e+11,9.810300e+10,3.007710e+11
"Fruits, Autres",1.571400e+10,0.000000e+00,7.285100e+10,0.000000e+00,6.696200e+10
Huile de Palme,2.974700e+10,1.856800e+10,2.561800e+10,0.000000e+00,6.833000e+09
Lait - Excl Beurre,8.841800e+10,1.233700e+10,3.426330e+11,2.721100e+10,3.003430e+11
"Légumes, Autres",2.817700e+10,0.000000e+00,8.710100e+10,3.980000e+09,7.571100e+10
Manioc,3.465500e+10,2.035500e+10,6.732600e+10,2.514900e+10,1.525700e+10
Maïs,1.024510e+11,1.821170e+11,7.010680e+11,4.028850e+11,5.591800e+10
"Oranges, Mandarines",2.294500e+10,1.000000e+06,1.953400e+10,0.000000e+00,1.919200e+10
Poissons Pelagiques,1.344500e+10,0.000000e+00,1.609400e+10,1.215600e+10,3.937000e+09
Pommes,8.518000e+09,0.000000e+00,1.559200e+10,0.000000e+00,1.455700e+10
Riz (Eq Blanchi),1.399000e+10,2.804000e+09,1.502340e+11,1.264400e+10,1.228320e+11
Soja,9.345500e+10,5.240000e+08,1.595700e+11,1.371000e+10,7.510000e+09
Sucre Eq Brut,3.420800e+10,2.996000e+09,7.845300e+10,0.000000e+00,6.497100e+10
Tomates,7.143000e+09,0.000000e+00,2.127700e+10,0.000000e+00,2.025200e+10

In [97]:
# calcul du ratio entre la quantité destinés aux "Autres utilisations" et la disponibilité intérieure
# création d'une nouvelle colonne résultante du ratio donné ci-dessus
s_3['Ratio Other uses/Di'] = s_3['Autres Utilisations']/s_3['Disponibilité intérieure']

In [98]:
# calcul du ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture
# création d'une nouvelle colonne résultante du ratio donné ci-dessus
s_3['Ratio Alim_ani/Food'] = s_3['Aliments pour animaux']/(s_3['Nourriture']+s_3['Aliments pour animaux'])
s_3

,Importations - Quantité,Autres Utilisations,Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio Other uses/Di,Ratio Alim_ani/Food
Produit,,,,,,,
Bananes,9.663000e+09,0.000000e+00,7.466000e+09,0.000000e+00,7.123000e+09,0.000000,0.000000
Blé,1.475760e+11,1.504700e+10,4.564750e+11,9.810300e+10,3.007710e+11,0.032963,0.245950
"Fruits, Autres",1.571400e+10,0.000000e+00,7.285100e+10,0.000000e+00,6.696200e+10,0.000000,0.000000
Huile de Palme,2.974700e+10,1.856800e+10,2.561800e+10,0.000000e+00,6.833000e+09,0.724803,0.000000
Lait - Excl Beurre,8.841800e+10,1.233700e+10,3.426330e+11,2.721100e+10,3.003430e+11,0.036006,0.083073
"Légumes, Autres",2.817700e+10,0.000000e+00,8.710100e+10,3.980000e+09,7.571100e+10,0.000000,0.049943
Manioc,3.465500e+10,2.035500e+10,6.732600e+10,2.514900e+10,1.525700e+10,0.302335,0.622408
Maïs,1.024510e+11,1.821170e+11,7.010680e+11,4.028850e+11,5.591800e+10,0.259771,0.878122
"Oranges, Mandarines",2.294500e+10,1.000000e+06,1.953400e+10,0.000000e+00,1.919200e+10,0.000051,0.000000
Poissons Pelagiques,1.344500e+10,0.000000e+00,1.609400e+10,1.215600e+10,3.937000e+09,0.000000,0.755359
Pommes,8.518000e+09,0.000000e+00,1.559200e+10,0.000000e+00,1.455700e+10,0.000000,0.000000
Riz (Eq Blanchi),1.399000e+10,2.804000e+09,1.502340e+11,1.264400e+10,1.228320e+11,0.018664,0.093330
Soja,9.345500e+10,5.240000e+08,1.595700e+11,1.371000e+10,7.510000e+09,0.003284,0.646089
Sucre Eq Brut,3.420800e+10,2.996000e+09,7.845300e+10,0.000000e+00,6.497100e+10,0.038188,0.000000
Tomates,7.143000e+09,0.000000e+00,2.127700e+10,0.000000e+00,2.025200e+10,0.000000,0.000000

# Question 12 : 
Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)

In [99]:
# tri descendant au sein du dataframe 
s_3.sort_values(by = 'Ratio Other uses/Di', ascending = False)[0:3]

,Importations - Quantité,Autres Utilisations,Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio Other uses/Di,Ratio Alim_ani/Food
Produit,,,,,,,
Huile de Palme,2.974700e+10,1.856800e+10,2.561800e+10,0.000000e+00,6.833000e+09,0.724803,0.000000
Manioc,3.465500e+10,2.035500e+10,6.732600e+10,2.514900e+10,1.525700e+10,0.302335,0.622408
Maïs,1.024510e+11,1.821170e+11,7.010680e+11,4.028850e+11,5.591800e+10,0.259771,0.878122

In [100]:
# tri descendant au sein du dataframe 
s_3.sort_values(by = 'Ratio Alim_ani/Food', ascending = False)[0:3]

,Importations - Quantité,Autres Utilisations,Disponibilité intérieure,Aliments pour animaux,Nourriture,Ratio Other uses/Di,Ratio Alim_ani/Food
Produit,,,,,,,
Maïs,1.024510e+11,1.821170e+11,7.010680e+11,4.028850e+11,5.591800e+10,0.259771,0.878122
Poissons Pelagiques,1.344500e+10,0.000000e+00,1.609400e+10,1.215600e+10,3.937000e+09,0.000000,0.755359
Soja,9.345500e+10,5.240000e+08,1.595700e+11,1.371000e+10,7.510000e+09,0.003284,0.646089

# Question 13 : 
Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?

In [101]:
# nous reprenons la table 'cer_alim_ani_2013' où ne sont conservées que les céréales destinées à l'alimentation 
# (humaine et animale)
cer_alim_ani_2013 = bilan_2013.loc[bilan_2013['is_cereal'] == 1, :]

In [102]:
# création d'une nouvelle table où ne sont conservées que les infos relatives aux USA
cer_alim_ani_2013_USA = cer_alim_ani_2013.loc[cer_alim_ani_2013['Code Pays'] == 231, :]

In [103]:
# calcul de la production de produits animaux 
cer_alim_ani_2013_USA['Aliments pour animaux'].sum(min_count=1)

140096000000.0

In [1]:
# proratisée à 10%
140096000000.0*0.10

14009600000.0

In [105]:
# ce qui amène à dire, que pour l'année 2013, si les USA diminuaient leur production de produits animaux de 10%,
# on pourrait libérer 14 009 600 000 tonnes de céréales

# Question 14 : 
En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?

In [106]:
# création d'un nouveau dataframe ne contenant que les infos relatives à la Thaïlande
bilan_2013_Thaïlande = bilan_2013.loc[bilan_2013['Pays']=="Thaïlande",:]
bilan_2013_Thaïlande.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut,is_prod_exp_ss_nut
13485,216,Thaïlande,2511,Blé,2013,1.130000e+09,0.0,76.0,10.93,0.23,...,0.0,20000000.0,0.0,1.858885e+12,53320652.7,2535.996098,0.072743,True,True,True
13486,216,Thaïlande,2513,Orge,2013,0.000000e+00,0.0,0.0,0.00,0.00,...,1000000.0,440000000.0,11000000.0,0.000000e+00,0.0,0.000000,0.000000,True,True,False
13487,216,Thaïlande,2514,Maïs,2013,3.724000e+09,0.0,95.0,10.16,1.04,...,24000000.0,144000000.0,0.0,2.323606e+12,60169176.9,3412.050551,0.088354,True,True,True
13488,216,Thaïlande,2515,Seigle,2013,0.000000e+00,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,True,True,False
13489,216,Thaïlande,2516,Avoine,2013,0.000000e+00,0.0,0.0,0.01,0.00,...,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,True,True,False

In [107]:
# création d'un nouveau dataframe ne contenant que les infos relatives au manioc
bilan_2013_Thaïlande_manioc = bilan_2013_Thaïlande.loc[bilan_2013_Thaïlande['Produit']=="Manioc",:]
bilan_2013_Thaïlande_manioc.head()

,Code Pays,Pays,Code Produit,Produit,Année,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Semences,Traitement,Variation de stock,Dispo alim kcal (kcal/pays/an),Dispo alim prot (kg/pays/an),"Ratio ""énergie/poids"" (kcal/kg)","Ratio ""poids de protéines/poids total"" (kg_prot/kg)",is_cereal,is_ss_nut,is_prod_exp_ss_nut
13494,216,Thaïlande,2532,Manioc,2013,1.800000e+09,2.081000e+09,40.0,13.0,0.05,...,0.0,0.0,0.0,9.783606e+11,3424262.1,1123.261309,0.003931,False,True,True

In [108]:
# sélection de la production de manioc
bilan_2013_Thaïlande_manioc.Production

13494    3.022800e+10
Name: Production, dtype: float64

In [109]:
# sélection de la quantité de manioc exportée
bilan_2013_Thaïlande_manioc['Exportations - Quantité']

13494    2.521400e+10
Name: Exportations - Quantité, dtype: float64

In [110]:
# calcul de la proportion de manioc exportée
bilan_2013_Thaïlande_manioc['Exportations - Quantité'] / bilan_2013_Thaïlande_manioc.Production

13494    0.834127
dtype: float64

In [111]:
# ce qui amène à dire que plus de 83% de la prodution de Manioc de la Thaïlande est destinée à l'exportation

In [112]:
# sélection de la valeur de personnes sous-alimentés en Thaïlande, nous sommes bien à l'unité par habitant
securite_2013.loc[securite_2013.Zone == 'Thaïlande', :]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
186,FS,Données de la sécurité alimentaire,216,Thaïlande,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6100000.0,F,Estimation FAO

In [113]:
# sélection de la valeur du nombre d'habitants en Thaïlande
population_2013.loc[population_2013.Zone == 'Thaïlande', :]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
212,OA,Séries temporelles annuelles,216,Thaïlande,511,Population totale,3010,Population-Estimations,2013,2013,1000 personnes,68143065.0,XU,"UNDESA, Population Division – World Population..."

In [114]:
# calcul de la proportion de personnes en sous-nutrition
6100000.0/68143065.0

0.0895175466498315

In [115]:
# ce qui amène à dire que la Thaïlande compte 9% de sa population en sous-nutrition